"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""

memo = {}

def calc_fib(n):
    if n <= 1:
        return n

    if n not in memo:
        memo[n] = calc_fib(n - 2) + calc_fib(n - 1)

    return memo[n]

fibSums = 0

i = 0

while(calc_fib(i) < (4 * pow(10, 6))):
    print(calc_fib(i), i)
    if (calc_fib(i) % 2 == 0):
        fibSums += calc_fib(i)

    i += 1

print(fibSums)
